project_name: tracetest
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  # discussion_category_name: General
  draft: false
  prerelease: auto
  ids:
  - cli
  - server
before:
  hooks:
  - dir: server
    cmd: go mod tidy

  - dir: cli
    cmd: go mod tidy
builds:
  - id: cli
    dir: ./cli
    binary: tracetest
    ldflags:
    - -X github.com/kubeshop/tracetest/cli/config.Version={{ if index .Env "VERSION"  }}{{ .Env.VERSION }}{{ else }}dev{{ end }}
    - -X github.com/kubeshop/tracetest/cli/config.Env={{ if index .Env "TRACETEST_ENV"  }}{{ .Env.TRACETEST_ENV }}{{ else }}dev{{ end }}
    - -X github.com/kubeshop/tracetest/cli/analytics.SecretKey={{ if index .Env "ANALYTICS_BE_KEY"  }}{{ .Env.ANALYTICS_BE_KEY }}{{ else }}{{ end }}
    env:
      - CGO_ENABLED=0

  - id: server
    dir: ./server
    binary: tracetest-server
    ldflags:
    - -X github.com/kubeshop/tracetest/server/app.Version={{ if index .Env "VERSION"  }}{{ .Env.VERSION }}{{ else }}dev{{ end }}
    - -X github.com/kubeshop/tracetest/server/app.Env={{ if index .Env "TRACETEST_ENV"  }}{{ .Env.TRACETEST_ENV }}{{ else }}dev{{ end }}
    - -X github.com/kubeshop/tracetest/server/analytics.SecretKey={{ if index .Env "ANALYTICS_BE_KEY"  }}{{ .Env.ANALYTICS_BE_KEY }}{{ else }}{{ end }}
    - -X github.com/kubeshop/tracetest/server/analytics.FrontendKey={{ if index .Env "ANALYTICS_FE_KEY"  }}{{ .Env.ANALYTICS_FE_KEY }}{{ else }}{{ end }}
    env:
      - CGO_ENABLED=0

archives:
- replacements:
    386: i386

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

universal_binaries:
- replace: true

nfpms:
- vendor: Kubeshop
  homepage: https://tracetest.kubeshop.io/
  maintainer: Sebastian Choren <sebastian@kubeshop.io>
  license: MIT
  formats:
    - deb
    - rpm
  replacements:
    386: i386
  deb:
    lintian_overrides:
      - statically-linked-binary

publishers:
  - name: fury.io
    env:
    - 'FURY_TOKEN={{ .Env.FURY_TOKEN }}'
    # relative to cli/, where goreleaser runs from
    cmd: ../scripts/fury-upload.sh {{ .ArtifactName }}

brews:
- tap:
    owner: kubeshop
    name: homebrew-tracetest
  commit_author:
    name: Brew Bot
    email: brewbot@kubeshop.io
  homepage: https://tracetest.kubeshop.io/
  license: "MIT"
