receivers:
  otlp:
    protocols:
      grpc:
      http:


processors:
  tail_sampling:
    decision_wait: 1s
    policies:
      - name: tracetest-spans
        type: trace_state
        trace_state: { key: tracetest, values: ["true"] }

  batch:
    timeout: 100ms

exporters:
  logging:
    loglevel: debug

  otlp/1:
    endpoint: tracetest:21321
    tls:
      insecure: true

  otlp/2:
    endpoint: data-prepper:21890
    tls:
      insecure: true
      insecure_skip_verify: true

  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true

  otlp/3:
    endpoint: tempo:4317
    tls:
      insecure: true

extensions:
  health_check: {}

service:
  extensions: [health_check]
  pipelines:
    traces/1:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/1, otlp/2, otlp/3, jaeger]
