postgresConnString: "host=postgres user=postgres password=postgres port=5432 sslmode=disable"

poolingConfig:
  maxWaitTimeForTrace: 30s
  retryDelay: 3s

googleAnalytics:
  enabled: false

demo:
  enabled: []

experimentalFeatures: []

telemetry:
  dataStores:
    opensearch:
      type: opensearch
      opensearch:
        addresses:
          - http://opensearch:9200
        index: traces
        username: example
        password: Example1#

  exporters:
    collector:
      serviceName: tracetest
      sampling: 100 # 100%
      exporter:
        type: collector
        collector:
          endpoint: otel-collector:4317

server:
  telemetry:
    dataStore: opensearch
    exporter: collector
    applicationExporter: collector
