openapi: 3.0.0
components:
  schemas:
    DataStoreConfig:
      type: object
      properties:
        dataStores:
          type: array
          items:
            $ref: "./dataStores.yaml#/components/schemas/DataStore"
        defaultDataStore:
          type: string
    TestConnectionResponse:
      type: object
      properties:
        connectivity:
          $ref: "#/components/schemas/ConnectionTestStep"
        authentication:
          $ref: "#/components/schemas/ConnectionTestStep"
        fetchTraces:
          $ref: "#/components/schemas/ConnectionTestStep"
    ConnectionResult:
      type: object
      properties:
        connectivity:
          $ref: "#/components/schemas/ConnectionTestStep"
        authentication:
          $ref: "#/components/schemas/ConnectionTestStep"
        fetchTraces:
          $ref: "#/components/schemas/ConnectionTestStep"
    ConnectionTestStep:
      type: object
      properties:
        passed:
          type: boolean
        message:
          type: string
        error:
          type: string
